### ISSUE TITLE
Which ACOLITE's  atmospheric correction is applied?

### ISSUE THREAD

**Issue by giustiandrea91** [miguelmendesduarte/EO_data#1]
Hello,

Could you please specify which ACOLITE's atmospheric correction you applied to the Sentinel-2 L1C products before extracting the spectral information for each class?  rayleigh reflectance or surface reflectance?

Thank you for your work. 

Andrea

**Comment by miguelmendesduarte** [comment]
Hello Andrea,

Thanks for your question. The answer is surface reflectance. You can read a detailed explanation of the Dark Spectrum Fitting algorithm (used by ACOLITE) at https://www.sciencedirect.com/science/article/pii/S0034425719301014?via%3Dihub#s0035 (Section 2.3.2).
Enjoy the data!
Kind regards,

Miguel
