### ISSUE TITLE
Request for Access to LFS Data Files

### ISSUE THREAD

**Issue by Imran4265** [miguelmendesduarte/EO_data#4]
Dear Miguel Durate, 

I hope this message finds you well. I am currently working with the repository "Floating-Marine-Debris-Data," and I encountered an issue while trying to access the large data files stored using Git LFS. It appears that the repository has exceeded its LFS data quota, which prevents me from downloading the necessary files.

The specific files I need for my project are:
- `data/all_data.csv`
- `data/balanced_data.csv`
- `data/synthetic_data.csv`
- `data/test.csv`
- `data/train.csv`

If possible, could you provide alternative access to these files? For instance, sharing them through email or a file-sharing service would be incredibly helpful.

Thank you for your time and assistance. I appreciate your support and look forward to your response.

Best regards,  
Imran Khan Patan  
imrankhanpatan996@gmail.com

**Comment by miguelmendesduarte** [comment]
Dear Imran,

Thank you for reaching out.
I apologize for the inconvenience caused by the LFS quota limitation.
I've just sent you an email with a link to a Google Drive folder containing all the data.
Please let me know if you have any trouble accessing the files.
Best,

Miguel

**Comment by Imran4265** [comment]
Dear Miguel Duarte,

I hope this email finds you well. Thank you for providing me with the data
for the Floating Marine Debris Detection project. I noticed that the data
is in the form of an Excel file, whereas I was initially expecting
satellite images.

Could you kindly clarify whether the Excel file contains pre-processed data
derived from the satellite images, or if it serves a different purpose? If
possible, I would appreciate any additional information or guidance on how
to use this data effectively for my project.

Thank you for your time and assistance.

Best regards,
Imran Khan Patan
