### ISSUE TITLE
Access to data

### ISSUE THREAD

**Issue by ConnorFlynn** [miguelmendesduarte/EO_data#5]
Hi Miguel, 

Thank you for sharing all of this amazing work! Students at our university have been exploring utilizing the model in new locations, [feel free to see their work here](https://github.com/NSF-ALL-SPICE-Alliance/marine-debris-ML). We're now revisiting the research and are requesting access to the data. I saw in another closed issue that you shared a google drive link. If you could share that with me at connor.flynn@chaminade.edu we would greatly appreciate it

Cheers,
Connor

**Comment by miguelmendesduarte** [comment]
Hey Connor,

I've just sent you an email with a link to a Google Drive folder containing all the data.
Please let me know if you have any trouble accessing the files.
Best,

Miguel

**Comment by ConnorFlynn** [comment]
Hey Miguel,

Thanks so much for your prompt response, I really appreciate your
dedication to open source data science. I'm sorry if I am missing it, but I
have checked all my email folders/github notifications and cant seem to
find the email with the link you shared to the data. Is there any
chance you can share again with ***@***.***

Thank you and Happy Holidays,
Connor
