### ISSUE TITLE
Error downloading object: data/all_data.csv 

### ISSUE THREAD

**Issue by szg666** [miguelmendesduarte/EO_data#6]
Error downloading object: data/all_data.csv (5fc5100): Smudge error: Error downloading data/all_data.csv (5fc510089b92658968c659eb4733be15f566191b0e596ebb98f9d55d8bcf1bae): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by miguelmendesduarte** [comment]
Thank you for reaching out and for your interest in my work!

As the datasets are quite large and were shared through GitHub LFS, there might be occasional download issues. To resolve this, I have uploaded the datasets to Google Drive for easier access. You can download them directly using [this link](https://drive.google.com/file/d/1iY3vg4-kfehKfsk4frPevwpjSotJ5Bfy/view).

If you need anything else or have questions along the way, feel free to reach out.
Kind regards,

Miguel
