### ISSUE TITLE
Request for Access for Dataset

### ISSUE THREAD

**Issue by rizabudi** [miguelmendesduarte/EO_data#7]
Dear Miguel M. Duarte,

I hope this message finds you well. My name is Riza Budi Prasetya, and I am a magister student at the Institute of Technology Sepuluh Nopember (ITS), Surabaya. I am currently conducting research on marine debris trajectories as part of my academic studies and am highly interested in the dataset hosted in your GitHub repository: [Floating Marine Debris Data](https://github.com/miguelmendesduarte/Floating-Marine-Debris-Data).

Your work and contributions in this area are incredibly valuable, and the data provided through your repository would significantly support my research. Specifically, I aim to use this dataset to validate and compare predictive models for marine debris trajectories, which are crucial for understanding and mitigating marine pollution.

Could you kindly grant me access to the dataset or provide guidance on how I may obtain it? If there are any terms, conditions, or acknowledgments necessary for using the dataset, I will be happy to adhere to them.

Thank you for your time and support. I would be delighted to share the outcomes of my research if it aligns with your interests. Please let me know if further details about my research or affiliation are required.

Looking forward to your response.

Best regards,
Riza Budi Prasetya
Magister Student
Institute of Technology Sepuluh Nopember (ITS), Surabaya
Email: riza.fun@gmail.com

**Comment by rizabudi** [comment]
cc @miguelmendesduarte

**Comment by miguelmendesduarte** [comment]
Thank you for reaching out and for your interest in my work!

As the datasets are quite large and were shared through GitHub LFS, there might be occasional download issues. To resolve this, I have uploaded the datasets to Google Drive for easier access. You can download them directly using [this link](https://drive.google.com/file/d/1iY3vg4-kfehKfsk4frPevwpjSotJ5Bfy/view).

If you need anything else or have questions along the way, feel free to reach out.
Kind regards,

Miguel

**Comment by rizabudi** [comment]
Thank you for your support @miguelmendesduarte 

I'll check the dataset
